Mobile version
iambenkis/Portfolio pull request #1
Opened 2022-06-29 21:01 UTC by iambenkis

2022-06-29 21:42 UTC, iambenkis commented
# Mobile Version of my Portfolio Site Skeleton.
  - [ ] Bug fix 
  - [ ] Run local stylelint config command(npx stylelint "**/*.{css,scss}" --fix.
# Checklist
 -[ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2022-06-29 22:34 UTC, Nemwel-Boniface requested changes
## Hello @iambenkis  :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Good job setting your portfolio you have done a tremendous job :clap:  :clap:  
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] Kindly note that you are supposed to stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122) as much as possible. You currently have a very large margin from the header ad the heading section. Kindly work on this.

Your design:
![Screenshot from 2022-06-30 01-13-23](https://user-images.githubusercontent.com/86318284/176556729-80bdbb84-5c2b-4c78-8ce7-14de447452d0.png)

Figma design:
![image](https://user-images.githubusercontent.com/86318284/176556879-b7599a64-d0db-4b5d-8ee9-d80fc9766437.png)

- Kindly make this change so it looks exactly similar to how the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122) is. 

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-29 22:34 UTC, Nemwel-Boniface commented on index.html
> +    </nav>
- [ ] Great job placing the nav bar inside a `<nav>` tag :clap:. How ever according to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md), this section is the header and thus should be wrapped inside a `<header>` tag. Kindly wrap the whole `<nav>` into a header so as making it look like this:

```
<header>
       <nav class="nav-bar">
        <h1 class="logo-txt">My Logo</h1>
        <i class="fa-solid fa-bars"></i>
    </nav> 
</header>
```

2022-06-29 22:34 UTC, Nemwel-Boniface commented on index.html
> +        <h1 class="logo-txt">My Logo</h1>
- [ ] Kindly note that your logo should be made a link as it is usually used to navigate back to the home page when someone has navigated to other pages. Changing it like below will fix it. 
```
        <h1 class="logo-txt"><a href="#">My Logo</a></h1>
```

2022-06-29 22:34 UTC, Nemwel-Boniface commented on index.html
> +    </header>
- [ ] Great job Benjamin you have very clean markup :+1: However, according to the [project's requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md), this section should not be inside a `<header>` tag but a `<section>` tag. Kindly change the `<header>` to `<section>` an this should be good.

2022-06-29 22:34 UTC, Nemwel-Boniface commented on style.css
> +}
- [ ] Kindly make sure to stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) as much as possible. This includes all typography, colors, margins, padding etc. Kindly change the `color: #091242;` to `color: #172B4D;` which is provided in the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
- [ ] Also, kindly make sure that this heading has a `font-weight: 700;` which is provided in the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

2022-06-29 22:34 UTC, Nemwel-Boniface commented on index.html
> +                <h2 class="connect-txt">LET'S CONNECT</h2>
- [ ] Let's kindly try to stick to the design as much as possible. The "Let's connect should be 16px". Kindly change this.

Your design:
![image](https://user-images.githubusercontent.com/86318284/176555766-d7fe5552-fd1b-4f68-bdeb-d63932e58e5e.png)

Figma design:
![image](https://user-images.githubusercontent.com/86318284/176555560-9af06dcb-1b1f-41fd-b527-9cd0cfc49d69.png)

2022-06-30 16:05 UTC, Kandy-Peter requested changes
Hi @iambenkis,

Good job so far! I know you have worked hard on implementing the changes requested by the previous reviewer. However, there is an issue that you still need to work on to go to the next project but you are almost there!

![image](https://user-images.githubusercontent.com/80612925/176716929-f241b39f-19b8-4917-ba42-9f7e7793fac8.png)


## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- You  are following GitHub actions :heavy_check_mark: 
## Required Changes ♻️

- [x] Kindly check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 16:05 UTC, Kandy-Peter commented on index.html
> +        </nav>
- [ ] As requested by the previous and following HMTL semantics, it would be better to wrap your nav inside the `header` HTML tag. Note that, the `<header>` tag in HTML is used to define the header for a document or a section as it contains the information related to the title and heading of the related content. Kindly add it.

2022-06-30 16:05 UTC, Kandy-Peter commented on index.html
> +            </h1>
- [ ] OPTIONAL: It would be better if you just use an `<a>` without wrapping it in the `<h1>` again.

2022-06-30 16:05 UTC, Kandy-Peter commented on index.html
> +            </h1>
- [ ] OPTIONAL:  To stick to the Figma design, you can separate the two sentences into different` hx` tags. 
```suggestion
            <h1>I'm Benjamin</h1>
            <h2> Glad to see   you!</h2>
```

**checkout how it looks on some mobile screen sizes:**
![image](https://user-images.githubusercontent.com/80612925/176724670-f34d3153-9399-4308-a5e7-6389a58ee721.png)

2022-06-30 16:33 UTC, iambenkis commented
Hello brother!
I don't understand what you said about wrapping the nav in the header
because I did  it .
If not, please let me know how to fix it.
Thanks

Le jeu. 30 juin 2022 à 18:05, Kandy Peter Kamuntu ***@***.***>
a écrit :

> ***@***.**** requested changes on this pull request.
>
> Hi @iambenkis <https://github.com/iambenkis>,
>
> Good job so far! I know you have worked hard on implementing the changes
> requested by the previous reviewer. However, there is an issue that you
> still need to work on to go to the next project but you are almost there!
>
> [image: image]
> <https://user-images.githubusercontent.com/80612925/176716929-f241b39f-19b8-4917-ba42-9f7e7793fac8.png>
> To highlight 🍾
>
>    - All linters are passing ✔️
>    - You are following GitHub actions ✔️
>
> Required Changes ♻️
>
>    - Kindly check the comments under the review.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/iambenkis/Portfolio/pull/1#discussion_r911198052>:
>
> > +    <section class="header">
>
> +        <!-- The navbar section  start-->
>
> +        <nav class="nav-bar">
>
> +            <h1 class="logo-txt">
>
> +                <a href="#">My Logo</a>
>
> +            </h1>
>
> +            <i class="fa-solid fa-bars"></i>
>
> +        </nav>
>
>
>
>    - As requested by the previous and following HMTL semantics, it would
>    be better to wrap your nav inside the header HTML tag. Note that, the
>    <header> tag in HTML is used to define the header for a document or a
>    section as it contains the information related to the title and heading of
>    the related content. Kindly add it.
>
> ------------------------------
>
> In index.html
> <https://github.com/iambenkis/Portfolio/pull/1#discussion_r911200274>:
>
> > +            <h1 class="logo-txt">
>
> +                <a href="#">My Logo</a>
>
> +            </h1>
>
>
>
>    - OPTIONAL: It would be better if you just use an <a> without wrapping
>    it in the <h1> again.
>
> ------------------------------
>
> In index.html
> <https://github.com/iambenkis/Portfolio/pull/1#discussion_r911203402>:
>
> > +            <h1>
>
> +                I'm Benjamin
>
> +                Glad to see   you!
>
> +            </h1>
>
>
>
>    - OPTIONAL: To stick to the Figma design, you can separate the two
>    sentences into different hx tags.
>
> ⬇️ Suggested change
>
> -            <h1>
>
> -                I'm Benjamin
>
> -                Glad to see   you!
>
> -            </h1>
>
> +            <h1>I'm Benjamin</h1>
>
> +            <h2> Glad to see   you!</h2>
>
>
> *checkout how it looks on some mobile screen sizes:*
> [image: image]
> <https://user-images.githubusercontent.com/80612925/176724670-f34d3153-9399-4308-a5e7-6389a58ee721.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/iambenkis/Portfolio/pull/1#pullrequestreview-1025124228>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATF3DV6RPVYCE522Q2SZBPLVRXAUFANCNFSM52HDW2DA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-30 16:46 UTC, Kandy-Peter commented
Hellow @iambenkis, 
You used a `section` tag with `class='header'`, but the requested change was to use the `<header>` tag. Check the example below:

```
<header>
       <nav class="nav-bar">
        <h1 class="logo-txt">My Logo</h1>
        <i class="fa-solid fa-bars"></i>
    </nav> 
</header>
```

2022-07-01 01:22 UTC, isaacpitwa approved these changes
# Approved 💯 ✅ 🥳 🎈 🎉 

Hi @iambenkis  , 👋🏻 

Your project is complete!  Please check the optional comments under the review.
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

## Highlights ✅ 
Highly organized and clean code ✔️ 👨🏻‍💻 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 


## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 01:22 UTC, isaacpitwa commented on index.html
> +        </nav>
- [ ] [OPTIONAL] Kindly move the header  closing tag  [here](https://github.com/iambenkis/Portfolio/blob/8abf9c8ca50f514992ed24fe431bfc3a5a8bf446/index.html#L46) to here (between line 22 (closing tag of nav) and the opening div (line 23)) in order to remove the headline not to be sematically part of the header. this will improve the sematics of your webside

2022-07-01 01:22 UTC, isaacpitwa commented on index.html
> +        <div class="container">
- [ ] [OPTIONAL] It would be useful to use more of sematic tags i.e use a `section` instead of a `div` to mark a webpage section for example headline.

2022-07-01 01:26 UTC, merged

2022-07-01 01:27 UTC, iambenkis commented
Thanks!

Le ven. 1 juil. 2022 à 03:22, Isaac Pitwa ***@***.***> a
écrit :

> ***@***.**** approved this pull request.
> Approved 💯 ✅ 🥳 🎈 🎉
>
> Hi @iambenkis <https://github.com/iambenkis> , 👋🏻
>
> Your project is complete! Please check the optional comments under the
> review.
> Congratulations! 🎉
>
>
> <https://camo.githubusercontent.com/b5642c8d710920270325423dcae1a20499406fa4ccda282bd63159f08d569018/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966>
> Highlights ✅
>
> Highly organized and clean code ✔️ 👨🏻‍💻
> Professional documentation ✔️
> Correct workflow ✔️
> Meaningful commit messages ✔️
> Optional suggestions
>
> Every comment with the [OPTIONAL] prefix is not crucial enough to stop the
> approval of this PR. However, I strongly recommend you to take them into
> account as they can make your code better.
>
> Check the comments under the review.
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/iambenkis/Portfolio/pull/1#discussion_r911536026>:
>
> > +    <script src="https://kit.fontawesome.com/8f76becb1e.js" crossorigin="anonymous"></script>
>
> +    <link rel="stylesheet" href="style.css">
>
> +    <link rel="preconnect" href="https://fonts.googleapis.com">
>
> +    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
>
> +    <link ***@***.***,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,400&display=swap" rel="stylesheet">
>
> +    <title>Portfolio</title>
>
> +</head>
>
> +<body>
>
> +
>
> +    <!-- header section start -->
>
> +    <header class="header">
>
> +        <!-- The navbar section  start-->
>
> +        <nav class="nav-bar">
>
> +            <a href="#" class="logo-txt">My Logo</a>
>
> +            <i class="fa-solid fa-bars"></i>
>
> +        </nav>
>
>
>
>    - [OPTIONAL] Kindly move the header closing tag here
>    <https://github.com/iambenkis/Portfolio/blob/8abf9c8ca50f514992ed24fe431bfc3a5a8bf446/index.html#L46>
>    to here (between line 22 (closing tag of nav) and the opening div (line
>    23)) in order to remove the headline not to be sematically part of the
>    header. this will improve the sematics of your webside
>
> ------------------------------
>
> In index.html
> <https://github.com/iambenkis/Portfolio/pull/1#discussion_r911536581>:
>
> > +    <link rel="stylesheet" href="style.css">
>
> +    <link rel="preconnect" href="https://fonts.googleapis.com">
>
> +    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
>
> +    <link ***@***.***,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,400&display=swap" rel="stylesheet">
>
> +    <title>Portfolio</title>
>
> +</head>
>
> +<body>
>
> +
>
> +    <!-- header section start -->
>
> +    <header class="header">
>
> +        <!-- The navbar section  start-->
>
> +        <nav class="nav-bar">
>
> +            <a href="#" class="logo-txt">My Logo</a>
>
> +            <i class="fa-solid fa-bars"></i>
>
> +        </nav>
>
> +        <div class="container">
>
>
>
>    - [OPTIONAL] It would be useful to use more of sematic tags i.e use a
>    section instead of a div to mark a webpage section for example
>    headline.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/iambenkis/Portfolio/pull/1#pullrequestreview-1025613097>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATF3DV4KFSMYYPHMIJEFW4LVRZB6NANCNFSM52HDW2DA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>