Milestone: Contact validation
iambenkis/Portfolio pull request #16
Opened 2022-07-21 20:12 UTC by iambenkis

# validate contact form
  # The contact-validation  branch contains code for the form validation. 
# Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] The project sticks to the Figma template
- [ ] If the validation is OK, the form will be sent. 
- [ ] If the validation is not OK, you show an error message  ````Kindly check your email```` and the form will be not sent.

2022-07-21 20:42 UTC, 1GORDON requested changes
##
## Hi @iambenkis & @DebbyMiressa ✋

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- Good commit messages ✔️
- Descriptive Pull request ✔️
- Linters are passing ✔️
- Professional Readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

_Check the comments under the review._

## Optional suggestions

- [ ] [Optional] You may kindly remove all commented code from your style sheet. Please check line `536`. Leaving commented code in your project is not regarded as a good practice.
- [ ] [Optional] You may as well remove commented code from your HTML file. Check out line `288`.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-21 20:42 UTC, 1GORDON commented on style.css
> +}
Great job team 🤝

- [ ] [Optional] I would recommend the error message be more explicit. Something like `Please make email lowercase`.

2022-07-21 20:42 UTC, 1GORDON commented on index.html
> +                        <button type="submit" id="submit">Get in Touch</button>
Great job team 🤝

- [ ] As specified in the project requirements, you may kindly align your button accordingly. Please check the design provided in the Figma template.
- Your design
![align button](https://user-images.githubusercontent.com/63917725/180310717-62db0ef9-336c-4365-b7b0-4c4adcd2f2ca.PNG)

- Figma design
![Figma design](https://user-images.githubusercontent.com/63917725/180311190-23c219de-90b1-40e0-ad8b-08e05e44eb2c.PNG)

2022-07-22 06:43 UTC, Nemwel-Boniface approved these changes
## Hello @iambenkis               :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the changes requested by the previous reviewer good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

- [ ] [OPTIONAL] - Kindly remove the commented out CSS code in style.css lines number 541 - 543.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-21 13:04 UTC, merged